// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
)

// AnnouncementCreate is the builder for creating a Announcement entity.
type AnnouncementCreate struct {
	config
	mutation *AnnouncementMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTitle sets the "title" field.
func (_c *AnnouncementCreate) SetTitle(v string) *AnnouncementCreate {
	_c.mutation.SetTitle(v)
	return _c
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableTitle(v *string) *AnnouncementCreate {
	if v != nil {
		_c.SetTitle(*v)
	}
	return _c
}

// SetContent sets the "content" field.
func (_c *AnnouncementCreate) SetContent(v string) *AnnouncementCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetType sets the "type" field.
func (_c *AnnouncementCreate) SetType(v announcement.Type) *AnnouncementCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableType(v *announcement.Type) *AnnouncementCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *AnnouncementCreate) SetSortOrder(v int) *AnnouncementCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableSortOrder(v *int) *AnnouncementCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *AnnouncementCreate) SetEnabled(v bool) *AnnouncementCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableEnabled(v *bool) *AnnouncementCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *AnnouncementCreate) SetStartTime(v time.Time) *AnnouncementCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableStartTime(v *time.Time) *AnnouncementCreate {
	if v != nil {
		_c.SetStartTime(*v)
	}
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *AnnouncementCreate) SetEndTime(v time.Time) *AnnouncementCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableEndTime(v *time.Time) *AnnouncementCreate {
	if v != nil {
		_c.SetEndTime(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AnnouncementCreate) SetCreatedAt(v time.Time) *AnnouncementCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableCreatedAt(v *time.Time) *AnnouncementCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AnnouncementCreate) SetUpdatedAt(v time.Time) *AnnouncementCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableUpdatedAt(v *time.Time) *AnnouncementCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *AnnouncementCreate) SetDeletedAt(v time.Time) *AnnouncementCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *AnnouncementCreate) SetNillableDeletedAt(v *time.Time) *AnnouncementCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// Mutation returns the AnnouncementMutation object of the builder.
func (_c *AnnouncementCreate) Mutation() *AnnouncementMutation {
	return _c.mutation
}

// Save creates the Announcement in the database.
func (_c *AnnouncementCreate) Save(ctx context.Context) (*Announcement, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AnnouncementCreate) SaveX(ctx context.Context) *Announcement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AnnouncementCreate) defaults() {
	if _, ok := _c.mutation.GetType(); !ok {
		v := announcement.DefaultType
		_c.mutation.SetType(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := announcement.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := announcement.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := announcement.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := announcement.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AnnouncementCreate) check() error {
	if v, ok := _c.mutation.Title(); ok {
		if err := announcement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Announcement.title": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Announcement.content"`)}
	}
	if v, ok := _c.mutation.Content(); ok {
		if err := announcement.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Announcement.content": %w`, err)}
		}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Announcement.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := announcement.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Announcement.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "Announcement.sort_order"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "Announcement.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Announcement.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Announcement.updated_at"`)}
	}
	return nil
}

func (_c *AnnouncementCreate) sqlSave(ctx context.Context) (*Announcement, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AnnouncementCreate) createSpec() (*Announcement, *sqlgraph.CreateSpec) {
	var (
		_node = &Announcement{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(announcement.Table, sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Title(); ok {
		_spec.SetField(announcement.FieldTitle, field.TypeString, value)
		_node.Title = &value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(announcement.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(announcement.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(announcement.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(announcement.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(announcement.FieldStartTime, field.TypeTime, value)
		_node.StartTime = &value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(announcement.FieldEndTime, field.TypeTime, value)
		_node.EndTime = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(announcement.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(announcement.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(announcement.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Announcement.Create().
//		SetTitle(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnnouncementUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *AnnouncementCreate) OnConflict(opts ...sql.ConflictOption) *AnnouncementUpsertOne {
	_c.conflict = opts
	return &AnnouncementUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Announcement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnnouncementCreate) OnConflictColumns(columns ...string) *AnnouncementUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnnouncementUpsertOne{
		create: _c,
	}
}

type (
	// AnnouncementUpsertOne is the builder for "upsert"-ing
	//  one Announcement node.
	AnnouncementUpsertOne struct {
		create *AnnouncementCreate
	}

	// AnnouncementUpsert is the "OnConflict" setter.
	AnnouncementUpsert struct {
		*sql.UpdateSet
	}
)

// SetTitle sets the "title" field.
func (u *AnnouncementUpsert) SetTitle(v string) *AnnouncementUpsert {
	u.Set(announcement.FieldTitle, v)
	return u
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *AnnouncementUpsert) UpdateTitle() *AnnouncementUpsert {
	u.SetExcluded(announcement.FieldTitle)
	return u
}

// ClearTitle clears the value of the "title" field.
func (u *AnnouncementUpsert) ClearTitle() *AnnouncementUpsert {
	u.SetNull(announcement.FieldTitle)
	return u
}

// SetContent sets the "content" field.
func (u *AnnouncementUpsert) SetContent(v string) *AnnouncementUpsert {
	u.Set(announcement.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *AnnouncementUpsert) UpdateContent() *AnnouncementUpsert {
	u.SetExcluded(announcement.FieldContent)
	return u
}

// SetType sets the "type" field.
func (u *AnnouncementUpsert) SetType(v announcement.Type) *AnnouncementUpsert {
	u.Set(announcement.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AnnouncementUpsert) UpdateType() *AnnouncementUpsert {
	u.SetExcluded(announcement.FieldType)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *AnnouncementUpsert) SetSortOrder(v int) *AnnouncementUpsert {
	u.Set(announcement.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AnnouncementUpsert) UpdateSortOrder() *AnnouncementUpsert {
	u.SetExcluded(announcement.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AnnouncementUpsert) AddSortOrder(v int) *AnnouncementUpsert {
	u.Add(announcement.FieldSortOrder, v)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *AnnouncementUpsert) SetEnabled(v bool) *AnnouncementUpsert {
	u.Set(announcement.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AnnouncementUpsert) UpdateEnabled() *AnnouncementUpsert {
	u.SetExcluded(announcement.FieldEnabled)
	return u
}

// SetStartTime sets the "start_time" field.
func (u *AnnouncementUpsert) SetStartTime(v time.Time) *AnnouncementUpsert {
	u.Set(announcement.FieldStartTime, v)
	return u
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *AnnouncementUpsert) UpdateStartTime() *AnnouncementUpsert {
	u.SetExcluded(announcement.FieldStartTime)
	return u
}

// ClearStartTime clears the value of the "start_time" field.
func (u *AnnouncementUpsert) ClearStartTime() *AnnouncementUpsert {
	u.SetNull(announcement.FieldStartTime)
	return u
}

// SetEndTime sets the "end_time" field.
func (u *AnnouncementUpsert) SetEndTime(v time.Time) *AnnouncementUpsert {
	u.Set(announcement.FieldEndTime, v)
	return u
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *AnnouncementUpsert) UpdateEndTime() *AnnouncementUpsert {
	u.SetExcluded(announcement.FieldEndTime)
	return u
}

// ClearEndTime clears the value of the "end_time" field.
func (u *AnnouncementUpsert) ClearEndTime() *AnnouncementUpsert {
	u.SetNull(announcement.FieldEndTime)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AnnouncementUpsert) SetUpdatedAt(v time.Time) *AnnouncementUpsert {
	u.Set(announcement.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AnnouncementUpsert) UpdateUpdatedAt() *AnnouncementUpsert {
	u.SetExcluded(announcement.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AnnouncementUpsert) SetDeletedAt(v time.Time) *AnnouncementUpsert {
	u.Set(announcement.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AnnouncementUpsert) UpdateDeletedAt() *AnnouncementUpsert {
	u.SetExcluded(announcement.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AnnouncementUpsert) ClearDeletedAt() *AnnouncementUpsert {
	u.SetNull(announcement.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Announcement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AnnouncementUpsertOne) UpdateNewValues() *AnnouncementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(announcement.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Announcement.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AnnouncementUpsertOne) Ignore() *AnnouncementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnnouncementUpsertOne) DoNothing() *AnnouncementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnnouncementCreate.OnConflict
// documentation for more info.
func (u *AnnouncementUpsertOne) Update(set func(*AnnouncementUpsert)) *AnnouncementUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnnouncementUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *AnnouncementUpsertOne) SetTitle(v string) *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *AnnouncementUpsertOne) UpdateTitle() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *AnnouncementUpsertOne) ClearTitle() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.ClearTitle()
	})
}

// SetContent sets the "content" field.
func (u *AnnouncementUpsertOne) SetContent(v string) *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *AnnouncementUpsertOne) UpdateContent() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateContent()
	})
}

// SetType sets the "type" field.
func (u *AnnouncementUpsertOne) SetType(v announcement.Type) *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AnnouncementUpsertOne) UpdateType() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateType()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AnnouncementUpsertOne) SetSortOrder(v int) *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AnnouncementUpsertOne) AddSortOrder(v int) *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AnnouncementUpsertOne) UpdateSortOrder() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateSortOrder()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AnnouncementUpsertOne) SetEnabled(v bool) *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AnnouncementUpsertOne) UpdateEnabled() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateEnabled()
	})
}

// SetStartTime sets the "start_time" field.
func (u *AnnouncementUpsertOne) SetStartTime(v time.Time) *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *AnnouncementUpsertOne) UpdateStartTime() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateStartTime()
	})
}

// ClearStartTime clears the value of the "start_time" field.
func (u *AnnouncementUpsertOne) ClearStartTime() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.ClearStartTime()
	})
}

// SetEndTime sets the "end_time" field.
func (u *AnnouncementUpsertOne) SetEndTime(v time.Time) *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *AnnouncementUpsertOne) UpdateEndTime() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "end_time" field.
func (u *AnnouncementUpsertOne) ClearEndTime() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.ClearEndTime()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AnnouncementUpsertOne) SetUpdatedAt(v time.Time) *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AnnouncementUpsertOne) UpdateUpdatedAt() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AnnouncementUpsertOne) SetDeletedAt(v time.Time) *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AnnouncementUpsertOne) UpdateDeletedAt() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AnnouncementUpsertOne) ClearDeletedAt() *AnnouncementUpsertOne {
	return u.Update(func(s *AnnouncementUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *AnnouncementUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnnouncementCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnnouncementUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AnnouncementUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AnnouncementUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// AnnouncementCreateBulk is the builder for creating many Announcement entities in bulk.
type AnnouncementCreateBulk struct {
	config
	err      error
	builders []*AnnouncementCreate
	conflict []sql.ConflictOption
}

// Save creates the Announcement entities in the database.
func (_c *AnnouncementCreateBulk) Save(ctx context.Context) ([]*Announcement, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Announcement, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AnnouncementMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AnnouncementCreateBulk) SaveX(ctx context.Context) []*Announcement {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AnnouncementCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AnnouncementCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Announcement.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AnnouncementUpsert) {
//			SetTitle(v+v).
//		}).
//		Exec(ctx)
func (_c *AnnouncementCreateBulk) OnConflict(opts ...sql.ConflictOption) *AnnouncementUpsertBulk {
	_c.conflict = opts
	return &AnnouncementUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Announcement.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *AnnouncementCreateBulk) OnConflictColumns(columns ...string) *AnnouncementUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &AnnouncementUpsertBulk{
		create: _c,
	}
}

// AnnouncementUpsertBulk is the builder for "upsert"-ing
// a bulk of Announcement nodes.
type AnnouncementUpsertBulk struct {
	create *AnnouncementCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Announcement.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AnnouncementUpsertBulk) UpdateNewValues() *AnnouncementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(announcement.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Announcement.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AnnouncementUpsertBulk) Ignore() *AnnouncementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AnnouncementUpsertBulk) DoNothing() *AnnouncementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AnnouncementCreateBulk.OnConflict
// documentation for more info.
func (u *AnnouncementUpsertBulk) Update(set func(*AnnouncementUpsert)) *AnnouncementUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AnnouncementUpsert{UpdateSet: update})
	}))
	return u
}

// SetTitle sets the "title" field.
func (u *AnnouncementUpsertBulk) SetTitle(v string) *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetTitle(v)
	})
}

// UpdateTitle sets the "title" field to the value that was provided on create.
func (u *AnnouncementUpsertBulk) UpdateTitle() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateTitle()
	})
}

// ClearTitle clears the value of the "title" field.
func (u *AnnouncementUpsertBulk) ClearTitle() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.ClearTitle()
	})
}

// SetContent sets the "content" field.
func (u *AnnouncementUpsertBulk) SetContent(v string) *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *AnnouncementUpsertBulk) UpdateContent() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateContent()
	})
}

// SetType sets the "type" field.
func (u *AnnouncementUpsertBulk) SetType(v announcement.Type) *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *AnnouncementUpsertBulk) UpdateType() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateType()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *AnnouncementUpsertBulk) SetSortOrder(v int) *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *AnnouncementUpsertBulk) AddSortOrder(v int) *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *AnnouncementUpsertBulk) UpdateSortOrder() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateSortOrder()
	})
}

// SetEnabled sets the "enabled" field.
func (u *AnnouncementUpsertBulk) SetEnabled(v bool) *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *AnnouncementUpsertBulk) UpdateEnabled() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateEnabled()
	})
}

// SetStartTime sets the "start_time" field.
func (u *AnnouncementUpsertBulk) SetStartTime(v time.Time) *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetStartTime(v)
	})
}

// UpdateStartTime sets the "start_time" field to the value that was provided on create.
func (u *AnnouncementUpsertBulk) UpdateStartTime() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateStartTime()
	})
}

// ClearStartTime clears the value of the "start_time" field.
func (u *AnnouncementUpsertBulk) ClearStartTime() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.ClearStartTime()
	})
}

// SetEndTime sets the "end_time" field.
func (u *AnnouncementUpsertBulk) SetEndTime(v time.Time) *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetEndTime(v)
	})
}

// UpdateEndTime sets the "end_time" field to the value that was provided on create.
func (u *AnnouncementUpsertBulk) UpdateEndTime() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateEndTime()
	})
}

// ClearEndTime clears the value of the "end_time" field.
func (u *AnnouncementUpsertBulk) ClearEndTime() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.ClearEndTime()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AnnouncementUpsertBulk) SetUpdatedAt(v time.Time) *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AnnouncementUpsertBulk) UpdateUpdatedAt() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AnnouncementUpsertBulk) SetDeletedAt(v time.Time) *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AnnouncementUpsertBulk) UpdateDeletedAt() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AnnouncementUpsertBulk) ClearDeletedAt() *AnnouncementUpsertBulk {
	return u.Update(func(s *AnnouncementUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *AnnouncementUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AnnouncementCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AnnouncementCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AnnouncementUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
