// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/announcement"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AnnouncementUpdate is the builder for updating Announcement entities.
type AnnouncementUpdate struct {
	config
	hooks    []Hook
	mutation *AnnouncementMutation
}

// Where appends a list predicates to the AnnouncementUpdate builder.
func (_u *AnnouncementUpdate) Where(ps ...predicate.Announcement) *AnnouncementUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *AnnouncementUpdate) SetTitle(v string) *AnnouncementUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableTitle(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *AnnouncementUpdate) ClearTitle() *AnnouncementUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetContent sets the "content" field.
func (_u *AnnouncementUpdate) SetContent(v string) *AnnouncementUpdate {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableContent(v *string) *AnnouncementUpdate {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AnnouncementUpdate) SetType(v announcement.Type) *AnnouncementUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableType(v *announcement.Type) *AnnouncementUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AnnouncementUpdate) SetSortOrder(v int) *AnnouncementUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableSortOrder(v *int) *AnnouncementUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AnnouncementUpdate) AddSortOrder(v int) *AnnouncementUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AnnouncementUpdate) SetEnabled(v bool) *AnnouncementUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableEnabled(v *bool) *AnnouncementUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *AnnouncementUpdate) SetStartTime(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableStartTime(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *AnnouncementUpdate) ClearStartTime() *AnnouncementUpdate {
	_u.mutation.ClearStartTime()
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *AnnouncementUpdate) SetEndTime(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableEndTime(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *AnnouncementUpdate) ClearEndTime() *AnnouncementUpdate {
	_u.mutation.ClearEndTime()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnnouncementUpdate) SetUpdatedAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AnnouncementUpdate) SetDeletedAt(v time.Time) *AnnouncementUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AnnouncementUpdate) SetNillableDeletedAt(v *time.Time) *AnnouncementUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AnnouncementUpdate) ClearDeletedAt() *AnnouncementUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the AnnouncementMutation object of the builder.
func (_u *AnnouncementUpdate) Mutation() *AnnouncementMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnnouncementUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnnouncementUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnnouncementUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := announcement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := announcement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Announcement.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := announcement.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Announcement.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := announcement.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Announcement.type": %w`, err)}
		}
	}
	return nil
}

func (_u *AnnouncementUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcement.Table, announcement.Columns, sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(announcement.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(announcement.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(announcement.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(announcement.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(announcement.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(announcement.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(announcement.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(announcement.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(announcement.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(announcement.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(announcement.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(announcement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(announcement.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(announcement.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnnouncementUpdateOne is the builder for updating a single Announcement entity.
type AnnouncementUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnnouncementMutation
}

// SetTitle sets the "title" field.
func (_u *AnnouncementUpdateOne) SetTitle(v string) *AnnouncementUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableTitle(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *AnnouncementUpdateOne) ClearTitle() *AnnouncementUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetContent sets the "content" field.
func (_u *AnnouncementUpdateOne) SetContent(v string) *AnnouncementUpdateOne {
	_u.mutation.SetContent(v)
	return _u
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableContent(v *string) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetContent(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AnnouncementUpdateOne) SetType(v announcement.Type) *AnnouncementUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableType(v *announcement.Type) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *AnnouncementUpdateOne) SetSortOrder(v int) *AnnouncementUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableSortOrder(v *int) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *AnnouncementUpdateOne) AddSortOrder(v int) *AnnouncementUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *AnnouncementUpdateOne) SetEnabled(v bool) *AnnouncementUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableEnabled(v *bool) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *AnnouncementUpdateOne) SetStartTime(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableStartTime(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// ClearStartTime clears the value of the "start_time" field.
func (_u *AnnouncementUpdateOne) ClearStartTime() *AnnouncementUpdateOne {
	_u.mutation.ClearStartTime()
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *AnnouncementUpdateOne) SetEndTime(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableEndTime(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *AnnouncementUpdateOne) ClearEndTime() *AnnouncementUpdateOne {
	_u.mutation.ClearEndTime()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnnouncementUpdateOne) SetUpdatedAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AnnouncementUpdateOne) SetDeletedAt(v time.Time) *AnnouncementUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AnnouncementUpdateOne) SetNillableDeletedAt(v *time.Time) *AnnouncementUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AnnouncementUpdateOne) ClearDeletedAt() *AnnouncementUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the AnnouncementMutation object of the builder.
func (_u *AnnouncementUpdateOne) Mutation() *AnnouncementMutation {
	return _u.mutation
}

// Where appends a list predicates to the AnnouncementUpdate builder.
func (_u *AnnouncementUpdateOne) Where(ps ...predicate.Announcement) *AnnouncementUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnnouncementUpdateOne) Select(field string, fields ...string) *AnnouncementUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Announcement entity.
func (_u *AnnouncementUpdateOne) Save(ctx context.Context) (*Announcement, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnnouncementUpdateOne) SaveX(ctx context.Context) *Announcement {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnnouncementUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnnouncementUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnnouncementUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := announcement.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnnouncementUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := announcement.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Announcement.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Content(); ok {
		if err := announcement.ContentValidator(v); err != nil {
			return &ValidationError{Name: "content", err: fmt.Errorf(`ent: validator failed for field "Announcement.content": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := announcement.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Announcement.type": %w`, err)}
		}
	}
	return nil
}

func (_u *AnnouncementUpdateOne) sqlSave(ctx context.Context) (_node *Announcement, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(announcement.Table, announcement.Columns, sqlgraph.NewFieldSpec(announcement.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Announcement.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, announcement.FieldID)
		for _, f := range fields {
			if !announcement.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != announcement.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(announcement.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(announcement.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Content(); ok {
		_spec.SetField(announcement.FieldContent, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(announcement.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(announcement.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(announcement.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(announcement.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(announcement.FieldStartTime, field.TypeTime, value)
	}
	if _u.mutation.StartTimeCleared() {
		_spec.ClearField(announcement.FieldStartTime, field.TypeTime)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(announcement.FieldEndTime, field.TypeTime, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(announcement.FieldEndTime, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(announcement.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(announcement.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(announcement.FieldDeletedAt, field.TypeTime)
	}
	_node = &Announcement{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{announcement.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
