// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/oauthprovider"
)

// OAuthProviderCreate is the builder for creating a OAuthProvider entity.
type OAuthProviderCreate struct {
	config
	mutation *OAuthProviderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetName sets the "name" field.
func (_c *OAuthProviderCreate) SetName(v string) *OAuthProviderCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *OAuthProviderCreate) SetDisplayName(v string) *OAuthProviderCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetClientID sets the "client_id" field.
func (_c *OAuthProviderCreate) SetClientID(v string) *OAuthProviderCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableClientID(v *string) *OAuthProviderCreate {
	if v != nil {
		_c.SetClientID(*v)
	}
	return _c
}

// SetClientSecret sets the "client_secret" field.
func (_c *OAuthProviderCreate) SetClientSecret(v string) *OAuthProviderCreate {
	_c.mutation.SetClientSecret(v)
	return _c
}

// SetNillableClientSecret sets the "client_secret" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableClientSecret(v *string) *OAuthProviderCreate {
	if v != nil {
		_c.SetClientSecret(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *OAuthProviderCreate) SetEnabled(v bool) *OAuthProviderCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableEnabled(v *bool) *OAuthProviderCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetConfig sets the "config" field.
func (_c *OAuthProviderCreate) SetConfig(v map[string]interface{}) *OAuthProviderCreate {
	_c.mutation.SetConfig(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthProviderCreate) SetCreatedAt(v time.Time) *OAuthProviderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableCreatedAt(v *time.Time) *OAuthProviderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthProviderCreate) SetUpdatedAt(v time.Time) *OAuthProviderCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthProviderCreate) SetNillableUpdatedAt(v *time.Time) *OAuthProviderCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the OAuthProviderMutation object of the builder.
func (_c *OAuthProviderCreate) Mutation() *OAuthProviderMutation {
	return _c.mutation
}

// Save creates the OAuthProvider in the database.
func (_c *OAuthProviderCreate) Save(ctx context.Context) (*OAuthProvider, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthProviderCreate) SaveX(ctx context.Context) *OAuthProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthProviderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthProviderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthProviderCreate) defaults() {
	if _, ok := _c.mutation.ClientID(); !ok {
		v := oauthprovider.DefaultClientID
		_c.mutation.SetClientID(v)
	}
	if _, ok := _c.mutation.ClientSecret(); !ok {
		v := oauthprovider.DefaultClientSecret
		_c.mutation.SetClientSecret(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := oauthprovider.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthprovider.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthprovider.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthProviderCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OAuthProvider.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := oauthprovider.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthProvider.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "OAuthProvider.display_name"`)}
	}
	if v, ok := _c.mutation.DisplayName(); ok {
		if err := oauthprovider.DisplayNameValidator(v); err != nil {
			return &ValidationError{Name: "display_name", err: fmt.Errorf(`ent: validator failed for field "OAuthProvider.display_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthProvider.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthprovider.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthProvider.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientSecret(); !ok {
		return &ValidationError{Name: "client_secret", err: errors.New(`ent: missing required field "OAuthProvider.client_secret"`)}
	}
	if v, ok := _c.mutation.ClientSecret(); ok {
		if err := oauthprovider.ClientSecretValidator(v); err != nil {
			return &ValidationError{Name: "client_secret", err: fmt.Errorf(`ent: validator failed for field "OAuthProvider.client_secret": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "OAuthProvider.enabled"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthProvider.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthProvider.updated_at"`)}
	}
	return nil
}

func (_c *OAuthProviderCreate) sqlSave(ctx context.Context) (*OAuthProvider, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthProviderCreate) createSpec() (*OAuthProvider, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthProvider{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthprovider.Table, sqlgraph.NewFieldSpec(oauthprovider.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oauthprovider.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(oauthprovider.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthprovider.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.ClientSecret(); ok {
		_spec.SetField(oauthprovider.FieldClientSecret, field.TypeString, value)
		_node.ClientSecret = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(oauthprovider.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.Config(); ok {
		_spec.SetField(oauthprovider.FieldConfig, field.TypeJSON, value)
		_node.Config = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthprovider.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthprovider.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthProvider.Create().
//		SetName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthProviderUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthProviderCreate) OnConflict(opts ...sql.ConflictOption) *OAuthProviderUpsertOne {
	_c.conflict = opts
	return &OAuthProviderUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthProviderCreate) OnConflictColumns(columns ...string) *OAuthProviderUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthProviderUpsertOne{
		create: _c,
	}
}

type (
	// OAuthProviderUpsertOne is the builder for "upsert"-ing
	//  one OAuthProvider node.
	OAuthProviderUpsertOne struct {
		create *OAuthProviderCreate
	}

	// OAuthProviderUpsert is the "OnConflict" setter.
	OAuthProviderUpsert struct {
		*sql.UpdateSet
	}
)

// SetName sets the "name" field.
func (u *OAuthProviderUpsert) SetName(v string) *OAuthProviderUpsert {
	u.Set(oauthprovider.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthProviderUpsert) UpdateName() *OAuthProviderUpsert {
	u.SetExcluded(oauthprovider.FieldName)
	return u
}

// SetDisplayName sets the "display_name" field.
func (u *OAuthProviderUpsert) SetDisplayName(v string) *OAuthProviderUpsert {
	u.Set(oauthprovider.FieldDisplayName, v)
	return u
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *OAuthProviderUpsert) UpdateDisplayName() *OAuthProviderUpsert {
	u.SetExcluded(oauthprovider.FieldDisplayName)
	return u
}

// SetClientID sets the "client_id" field.
func (u *OAuthProviderUpsert) SetClientID(v string) *OAuthProviderUpsert {
	u.Set(oauthprovider.FieldClientID, v)
	return u
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthProviderUpsert) UpdateClientID() *OAuthProviderUpsert {
	u.SetExcluded(oauthprovider.FieldClientID)
	return u
}

// SetClientSecret sets the "client_secret" field.
func (u *OAuthProviderUpsert) SetClientSecret(v string) *OAuthProviderUpsert {
	u.Set(oauthprovider.FieldClientSecret, v)
	return u
}

// UpdateClientSecret sets the "client_secret" field to the value that was provided on create.
func (u *OAuthProviderUpsert) UpdateClientSecret() *OAuthProviderUpsert {
	u.SetExcluded(oauthprovider.FieldClientSecret)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *OAuthProviderUpsert) SetEnabled(v bool) *OAuthProviderUpsert {
	u.Set(oauthprovider.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OAuthProviderUpsert) UpdateEnabled() *OAuthProviderUpsert {
	u.SetExcluded(oauthprovider.FieldEnabled)
	return u
}

// SetConfig sets the "config" field.
func (u *OAuthProviderUpsert) SetConfig(v map[string]interface{}) *OAuthProviderUpsert {
	u.Set(oauthprovider.FieldConfig, v)
	return u
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *OAuthProviderUpsert) UpdateConfig() *OAuthProviderUpsert {
	u.SetExcluded(oauthprovider.FieldConfig)
	return u
}

// ClearConfig clears the value of the "config" field.
func (u *OAuthProviderUpsert) ClearConfig() *OAuthProviderUpsert {
	u.SetNull(oauthprovider.FieldConfig)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthProviderUpsert) SetUpdatedAt(v time.Time) *OAuthProviderUpsert {
	u.Set(oauthprovider.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthProviderUpsert) UpdateUpdatedAt() *OAuthProviderUpsert {
	u.SetExcluded(oauthprovider.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.OAuthProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthProviderUpsertOne) UpdateNewValues() *OAuthProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(oauthprovider.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthProvider.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OAuthProviderUpsertOne) Ignore() *OAuthProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthProviderUpsertOne) DoNothing() *OAuthProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthProviderCreate.OnConflict
// documentation for more info.
func (u *OAuthProviderUpsertOne) Update(set func(*OAuthProviderUpsert)) *OAuthProviderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *OAuthProviderUpsertOne) SetName(v string) *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthProviderUpsertOne) UpdateName() *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *OAuthProviderUpsertOne) SetDisplayName(v string) *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *OAuthProviderUpsertOne) UpdateDisplayName() *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateDisplayName()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthProviderUpsertOne) SetClientID(v string) *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthProviderUpsertOne) UpdateClientID() *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateClientID()
	})
}

// SetClientSecret sets the "client_secret" field.
func (u *OAuthProviderUpsertOne) SetClientSecret(v string) *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetClientSecret(v)
	})
}

// UpdateClientSecret sets the "client_secret" field to the value that was provided on create.
func (u *OAuthProviderUpsertOne) UpdateClientSecret() *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateClientSecret()
	})
}

// SetEnabled sets the "enabled" field.
func (u *OAuthProviderUpsertOne) SetEnabled(v bool) *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OAuthProviderUpsertOne) UpdateEnabled() *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateEnabled()
	})
}

// SetConfig sets the "config" field.
func (u *OAuthProviderUpsertOne) SetConfig(v map[string]interface{}) *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *OAuthProviderUpsertOne) UpdateConfig() *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *OAuthProviderUpsertOne) ClearConfig() *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.ClearConfig()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthProviderUpsertOne) SetUpdatedAt(v time.Time) *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthProviderUpsertOne) UpdateUpdatedAt() *OAuthProviderUpsertOne {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OAuthProviderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthProviderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthProviderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OAuthProviderUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OAuthProviderUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// OAuthProviderCreateBulk is the builder for creating many OAuthProvider entities in bulk.
type OAuthProviderCreateBulk struct {
	config
	err      error
	builders []*OAuthProviderCreate
	conflict []sql.ConflictOption
}

// Save creates the OAuthProvider entities in the database.
func (_c *OAuthProviderCreateBulk) Save(ctx context.Context) ([]*OAuthProvider, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthProvider, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthProviderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthProviderCreateBulk) SaveX(ctx context.Context) []*OAuthProvider {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthProviderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthProviderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.OAuthProvider.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OAuthProviderUpsert) {
//			SetName(v+v).
//		}).
//		Exec(ctx)
func (_c *OAuthProviderCreateBulk) OnConflict(opts ...sql.ConflictOption) *OAuthProviderUpsertBulk {
	_c.conflict = opts
	return &OAuthProviderUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.OAuthProvider.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *OAuthProviderCreateBulk) OnConflictColumns(columns ...string) *OAuthProviderUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &OAuthProviderUpsertBulk{
		create: _c,
	}
}

// OAuthProviderUpsertBulk is the builder for "upsert"-ing
// a bulk of OAuthProvider nodes.
type OAuthProviderUpsertBulk struct {
	create *OAuthProviderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.OAuthProvider.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OAuthProviderUpsertBulk) UpdateNewValues() *OAuthProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(oauthprovider.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.OAuthProvider.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OAuthProviderUpsertBulk) Ignore() *OAuthProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OAuthProviderUpsertBulk) DoNothing() *OAuthProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OAuthProviderCreateBulk.OnConflict
// documentation for more info.
func (u *OAuthProviderUpsertBulk) Update(set func(*OAuthProviderUpsert)) *OAuthProviderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OAuthProviderUpsert{UpdateSet: update})
	}))
	return u
}

// SetName sets the "name" field.
func (u *OAuthProviderUpsertBulk) SetName(v string) *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *OAuthProviderUpsertBulk) UpdateName() *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateName()
	})
}

// SetDisplayName sets the "display_name" field.
func (u *OAuthProviderUpsertBulk) SetDisplayName(v string) *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetDisplayName(v)
	})
}

// UpdateDisplayName sets the "display_name" field to the value that was provided on create.
func (u *OAuthProviderUpsertBulk) UpdateDisplayName() *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateDisplayName()
	})
}

// SetClientID sets the "client_id" field.
func (u *OAuthProviderUpsertBulk) SetClientID(v string) *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetClientID(v)
	})
}

// UpdateClientID sets the "client_id" field to the value that was provided on create.
func (u *OAuthProviderUpsertBulk) UpdateClientID() *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateClientID()
	})
}

// SetClientSecret sets the "client_secret" field.
func (u *OAuthProviderUpsertBulk) SetClientSecret(v string) *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetClientSecret(v)
	})
}

// UpdateClientSecret sets the "client_secret" field to the value that was provided on create.
func (u *OAuthProviderUpsertBulk) UpdateClientSecret() *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateClientSecret()
	})
}

// SetEnabled sets the "enabled" field.
func (u *OAuthProviderUpsertBulk) SetEnabled(v bool) *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *OAuthProviderUpsertBulk) UpdateEnabled() *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateEnabled()
	})
}

// SetConfig sets the "config" field.
func (u *OAuthProviderUpsertBulk) SetConfig(v map[string]interface{}) *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetConfig(v)
	})
}

// UpdateConfig sets the "config" field to the value that was provided on create.
func (u *OAuthProviderUpsertBulk) UpdateConfig() *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateConfig()
	})
}

// ClearConfig clears the value of the "config" field.
func (u *OAuthProviderUpsertBulk) ClearConfig() *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.ClearConfig()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OAuthProviderUpsertBulk) SetUpdatedAt(v time.Time) *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OAuthProviderUpsertBulk) UpdateUpdatedAt() *OAuthProviderUpsertBulk {
	return u.Update(func(s *OAuthProviderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *OAuthProviderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OAuthProviderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OAuthProviderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OAuthProviderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
