// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/paymentorder"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/product"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdate) SetUpdatedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PaymentOrderUpdate) SetDeletedAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableDeletedAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PaymentOrderUpdate) ClearDeletedAt() *PaymentOrderUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdate) SetUserID(v int64) *PaymentOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableUserID(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *PaymentOrderUpdate) SetProductID(v int64) *PaymentOrderUpdate {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableProductID(v *int64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *PaymentOrderUpdate) ClearProductID() *PaymentOrderUpdate {
	_u.mutation.ClearProductID()
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *PaymentOrderUpdate) SetOrderNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableOrderNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *PaymentOrderUpdate) SetTradeNo(v string) *PaymentOrderUpdate {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableTradeNo(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *PaymentOrderUpdate) ClearTradeNo() *PaymentOrderUpdate {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetAmountCny sets the "amount_cny" field.
func (_u *PaymentOrderUpdate) SetAmountCny(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetAmountCny()
	_u.mutation.SetAmountCny(v)
	return _u
}

// SetNillableAmountCny sets the "amount_cny" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmountCny(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmountCny(*v)
	}
	return _u
}

// AddAmountCny adds value to the "amount_cny" field.
func (_u *PaymentOrderUpdate) AddAmountCny(v float64) *PaymentOrderUpdate {
	_u.mutation.AddAmountCny(v)
	return _u
}

// SetAmountValue sets the "amount_value" field.
func (_u *PaymentOrderUpdate) SetAmountValue(v float64) *PaymentOrderUpdate {
	_u.mutation.ResetAmountValue()
	_u.mutation.SetAmountValue(v)
	return _u
}

// SetNillableAmountValue sets the "amount_value" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmountValue(v *float64) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmountValue(*v)
	}
	return _u
}

// AddAmountValue adds value to the "amount_value" field.
func (_u *PaymentOrderUpdate) AddAmountValue(v float64) *PaymentOrderUpdate {
	_u.mutation.AddAmountValue(v)
	return _u
}

// SetOrderType sets the "order_type" field.
func (_u *PaymentOrderUpdate) SetOrderType(v paymentorder.OrderType) *PaymentOrderUpdate {
	_u.mutation.SetOrderType(v)
	return _u
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableOrderType(v *paymentorder.OrderType) *PaymentOrderUpdate {
	if v != nil {
		_u.SetOrderType(*v)
	}
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *PaymentOrderUpdate) SetPaymentMethod(v paymentorder.PaymentMethod) *PaymentOrderUpdate {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePaymentMethod(v *paymentorder.PaymentMethod) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdate) SetStatus(v paymentorder.Status) *PaymentOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableStatus(v *paymentorder.Status) *PaymentOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdate) SetPaidAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdate) ClearPaidAt() *PaymentOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetCallbackData sets the "callback_data" field.
func (_u *PaymentOrderUpdate) SetCallbackData(v map[string]interface{}) *PaymentOrderUpdate {
	_u.mutation.SetCallbackData(v)
	return _u
}

// ClearCallbackData clears the value of the "callback_data" field.
func (_u *PaymentOrderUpdate) ClearCallbackData() *PaymentOrderUpdate {
	_u.mutation.ClearCallbackData()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *PaymentOrderUpdate) SetRemark(v string) *PaymentOrderUpdate {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableRemark(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *PaymentOrderUpdate) ClearRemark() *PaymentOrderUpdate {
	_u.mutation.ClearRemark()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) SetUser(v *User) *PaymentOrderUpdate {
	return _u.SetUserID(v.ID)
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *PaymentOrderUpdate) SetProduct(v *Product) *PaymentOrderUpdate {
	return _u.SetProductID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) ClearUser() *PaymentOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *PaymentOrderUpdate) ClearProduct() *PaymentOrderUpdate {
	_u.mutation.ClearProduct()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if paymentorder.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentorder.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdate) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := paymentorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderType(); ok {
		if err := paymentorder.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := paymentorder.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.payment_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(paymentorder.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(paymentorder.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(paymentorder.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(paymentorder.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.AmountCny(); ok {
		_spec.SetField(paymentorder.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCny(); ok {
		_spec.AddField(paymentorder.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountValue(); ok {
		_spec.SetField(paymentorder.FieldAmountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountValue(); ok {
		_spec.AddField(paymentorder.FieldAmountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OrderType(); ok {
		_spec.SetField(paymentorder.FieldOrderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(paymentorder.FieldPaymentMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CallbackData(); ok {
		_spec.SetField(paymentorder.FieldCallbackData, field.TypeJSON, value)
	}
	if _u.mutation.CallbackDataCleared() {
		_spec.ClearField(paymentorder.FieldCallbackData, field.TypeJSON)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(paymentorder.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(paymentorder.FieldRemark, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.ProductTable,
			Columns: []string{paymentorder.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.ProductTable,
			Columns: []string{paymentorder.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentOrderUpdateOne) SetUpdatedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *PaymentOrderUpdateOne) SetDeletedAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableDeletedAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *PaymentOrderUpdateOne) ClearDeletedAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdateOne) SetUserID(v int64) *PaymentOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableUserID(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProductID sets the "product_id" field.
func (_u *PaymentOrderUpdateOne) SetProductID(v int64) *PaymentOrderUpdateOne {
	_u.mutation.SetProductID(v)
	return _u
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableProductID(v *int64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetProductID(*v)
	}
	return _u
}

// ClearProductID clears the value of the "product_id" field.
func (_u *PaymentOrderUpdateOne) ClearProductID() *PaymentOrderUpdateOne {
	_u.mutation.ClearProductID()
	return _u
}

// SetOrderNo sets the "order_no" field.
func (_u *PaymentOrderUpdateOne) SetOrderNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetOrderNo(v)
	return _u
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableOrderNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetOrderNo(*v)
	}
	return _u
}

// SetTradeNo sets the "trade_no" field.
func (_u *PaymentOrderUpdateOne) SetTradeNo(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetTradeNo(v)
	return _u
}

// SetNillableTradeNo sets the "trade_no" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableTradeNo(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetTradeNo(*v)
	}
	return _u
}

// ClearTradeNo clears the value of the "trade_no" field.
func (_u *PaymentOrderUpdateOne) ClearTradeNo() *PaymentOrderUpdateOne {
	_u.mutation.ClearTradeNo()
	return _u
}

// SetAmountCny sets the "amount_cny" field.
func (_u *PaymentOrderUpdateOne) SetAmountCny(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmountCny()
	_u.mutation.SetAmountCny(v)
	return _u
}

// SetNillableAmountCny sets the "amount_cny" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmountCny(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmountCny(*v)
	}
	return _u
}

// AddAmountCny adds value to the "amount_cny" field.
func (_u *PaymentOrderUpdateOne) AddAmountCny(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddAmountCny(v)
	return _u
}

// SetAmountValue sets the "amount_value" field.
func (_u *PaymentOrderUpdateOne) SetAmountValue(v float64) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmountValue()
	_u.mutation.SetAmountValue(v)
	return _u
}

// SetNillableAmountValue sets the "amount_value" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmountValue(v *float64) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmountValue(*v)
	}
	return _u
}

// AddAmountValue adds value to the "amount_value" field.
func (_u *PaymentOrderUpdateOne) AddAmountValue(v float64) *PaymentOrderUpdateOne {
	_u.mutation.AddAmountValue(v)
	return _u
}

// SetOrderType sets the "order_type" field.
func (_u *PaymentOrderUpdateOne) SetOrderType(v paymentorder.OrderType) *PaymentOrderUpdateOne {
	_u.mutation.SetOrderType(v)
	return _u
}

// SetNillableOrderType sets the "order_type" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableOrderType(v *paymentorder.OrderType) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetOrderType(*v)
	}
	return _u
}

// SetPaymentMethod sets the "payment_method" field.
func (_u *PaymentOrderUpdateOne) SetPaymentMethod(v paymentorder.PaymentMethod) *PaymentOrderUpdateOne {
	_u.mutation.SetPaymentMethod(v)
	return _u
}

// SetNillablePaymentMethod sets the "payment_method" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePaymentMethod(v *paymentorder.PaymentMethod) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPaymentMethod(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdateOne) SetStatus(v paymentorder.Status) *PaymentOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableStatus(v *paymentorder.Status) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdateOne) SetPaidAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdateOne) ClearPaidAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetCallbackData sets the "callback_data" field.
func (_u *PaymentOrderUpdateOne) SetCallbackData(v map[string]interface{}) *PaymentOrderUpdateOne {
	_u.mutation.SetCallbackData(v)
	return _u
}

// ClearCallbackData clears the value of the "callback_data" field.
func (_u *PaymentOrderUpdateOne) ClearCallbackData() *PaymentOrderUpdateOne {
	_u.mutation.ClearCallbackData()
	return _u
}

// SetRemark sets the "remark" field.
func (_u *PaymentOrderUpdateOne) SetRemark(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetRemark(v)
	return _u
}

// SetNillableRemark sets the "remark" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableRemark(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetRemark(*v)
	}
	return _u
}

// ClearRemark clears the value of the "remark" field.
func (_u *PaymentOrderUpdateOne) ClearRemark() *PaymentOrderUpdateOne {
	_u.mutation.ClearRemark()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) SetUser(v *User) *PaymentOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetProduct sets the "product" edge to the Product entity.
func (_u *PaymentOrderUpdateOne) SetProduct(v *Product) *PaymentOrderUpdateOne {
	return _u.SetProductID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) ClearUser() *PaymentOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearProduct clears the "product" edge to the Product entity.
func (_u *PaymentOrderUpdateOne) ClearProduct() *PaymentOrderUpdateOne {
	_u.mutation.ClearProduct()
	return _u
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrder entity.
func (_u *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentOrderUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if paymentorder.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized paymentorder.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := paymentorder.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdateOne) check() error {
	if v, ok := _u.mutation.OrderNo(); ok {
		if err := paymentorder.OrderNoValidator(v); err != nil {
			return &ValidationError{Name: "order_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TradeNo(); ok {
		if err := paymentorder.TradeNoValidator(v); err != nil {
			return &ValidationError{Name: "trade_no", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.trade_no": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OrderType(); ok {
		if err := paymentorder.OrderTypeValidator(v); err != nil {
			return &ValidationError{Name: "order_type", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.order_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PaymentMethod(); ok {
		if err := paymentorder.PaymentMethodValidator(v); err != nil {
			return &ValidationError{Name: "payment_method", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.payment_method": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentorder.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(paymentorder.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(paymentorder.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.OrderNo(); ok {
		_spec.SetField(paymentorder.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := _u.mutation.TradeNo(); ok {
		_spec.SetField(paymentorder.FieldTradeNo, field.TypeString, value)
	}
	if _u.mutation.TradeNoCleared() {
		_spec.ClearField(paymentorder.FieldTradeNo, field.TypeString)
	}
	if value, ok := _u.mutation.AmountCny(); ok {
		_spec.SetField(paymentorder.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCny(); ok {
		_spec.AddField(paymentorder.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AmountValue(); ok {
		_spec.SetField(paymentorder.FieldAmountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountValue(); ok {
		_spec.AddField(paymentorder.FieldAmountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.OrderType(); ok {
		_spec.SetField(paymentorder.FieldOrderType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaymentMethod(); ok {
		_spec.SetField(paymentorder.FieldPaymentMethod, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CallbackData(); ok {
		_spec.SetField(paymentorder.FieldCallbackData, field.TypeJSON, value)
	}
	if _u.mutation.CallbackDataCleared() {
		_spec.ClearField(paymentorder.FieldCallbackData, field.TypeJSON)
	}
	if value, ok := _u.mutation.Remark(); ok {
		_spec.SetField(paymentorder.FieldRemark, field.TypeString, value)
	}
	if _u.mutation.RemarkCleared() {
		_spec.ClearField(paymentorder.FieldRemark, field.TypeString)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProductCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.ProductTable,
			Columns: []string{paymentorder.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.ProductTable,
			Columns: []string{paymentorder.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(product.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
