// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/useroauthbinding"
)

// UserOAuthBindingUpdate is the builder for updating UserOAuthBinding entities.
type UserOAuthBindingUpdate struct {
	config
	hooks    []Hook
	mutation *UserOAuthBindingMutation
}

// Where appends a list predicates to the UserOAuthBindingUpdate builder.
func (_u *UserOAuthBindingUpdate) Where(ps ...predicate.UserOAuthBinding) *UserOAuthBindingUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserOAuthBindingUpdate) SetUserID(v int64) *UserOAuthBindingUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserOAuthBindingUpdate) SetNillableUserID(v *int64) *UserOAuthBindingUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UserOAuthBindingUpdate) SetProvider(v string) *UserOAuthBindingUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UserOAuthBindingUpdate) SetNillableProvider(v *string) *UserOAuthBindingUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderUserID sets the "provider_user_id" field.
func (_u *UserOAuthBindingUpdate) SetProviderUserID(v string) *UserOAuthBindingUpdate {
	_u.mutation.SetProviderUserID(v)
	return _u
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (_u *UserOAuthBindingUpdate) SetNillableProviderUserID(v *string) *UserOAuthBindingUpdate {
	if v != nil {
		_u.SetProviderUserID(*v)
	}
	return _u
}

// SetProviderEmail sets the "provider_email" field.
func (_u *UserOAuthBindingUpdate) SetProviderEmail(v string) *UserOAuthBindingUpdate {
	_u.mutation.SetProviderEmail(v)
	return _u
}

// SetNillableProviderEmail sets the "provider_email" field if the given value is not nil.
func (_u *UserOAuthBindingUpdate) SetNillableProviderEmail(v *string) *UserOAuthBindingUpdate {
	if v != nil {
		_u.SetProviderEmail(*v)
	}
	return _u
}

// ClearProviderEmail clears the value of the "provider_email" field.
func (_u *UserOAuthBindingUpdate) ClearProviderEmail() *UserOAuthBindingUpdate {
	_u.mutation.ClearProviderEmail()
	return _u
}

// SetProviderUsername sets the "provider_username" field.
func (_u *UserOAuthBindingUpdate) SetProviderUsername(v string) *UserOAuthBindingUpdate {
	_u.mutation.SetProviderUsername(v)
	return _u
}

// SetNillableProviderUsername sets the "provider_username" field if the given value is not nil.
func (_u *UserOAuthBindingUpdate) SetNillableProviderUsername(v *string) *UserOAuthBindingUpdate {
	if v != nil {
		_u.SetProviderUsername(*v)
	}
	return _u
}

// ClearProviderUsername clears the value of the "provider_username" field.
func (_u *UserOAuthBindingUpdate) ClearProviderUsername() *UserOAuthBindingUpdate {
	_u.mutation.ClearProviderUsername()
	return _u
}

// SetProviderAvatar sets the "provider_avatar" field.
func (_u *UserOAuthBindingUpdate) SetProviderAvatar(v string) *UserOAuthBindingUpdate {
	_u.mutation.SetProviderAvatar(v)
	return _u
}

// SetNillableProviderAvatar sets the "provider_avatar" field if the given value is not nil.
func (_u *UserOAuthBindingUpdate) SetNillableProviderAvatar(v *string) *UserOAuthBindingUpdate {
	if v != nil {
		_u.SetProviderAvatar(*v)
	}
	return _u
}

// ClearProviderAvatar clears the value of the "provider_avatar" field.
func (_u *UserOAuthBindingUpdate) ClearProviderAvatar() *UserOAuthBindingUpdate {
	_u.mutation.ClearProviderAvatar()
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *UserOAuthBindingUpdate) SetAccessToken(v string) *UserOAuthBindingUpdate {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *UserOAuthBindingUpdate) SetNillableAccessToken(v *string) *UserOAuthBindingUpdate {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *UserOAuthBindingUpdate) ClearAccessToken() *UserOAuthBindingUpdate {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UserOAuthBindingUpdate) SetRefreshToken(v string) *UserOAuthBindingUpdate {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UserOAuthBindingUpdate) SetNillableRefreshToken(v *string) *UserOAuthBindingUpdate {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UserOAuthBindingUpdate) ClearRefreshToken() *UserOAuthBindingUpdate {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserOAuthBindingUpdate) SetUpdatedAt(v time.Time) *UserOAuthBindingUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserOAuthBindingUpdate) SetUser(v *User) *UserOAuthBindingUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserOAuthBindingMutation object of the builder.
func (_u *UserOAuthBindingUpdate) Mutation() *UserOAuthBindingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserOAuthBindingUpdate) ClearUser() *UserOAuthBindingUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserOAuthBindingUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserOAuthBindingUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserOAuthBindingUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserOAuthBindingUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserOAuthBindingUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useroauthbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserOAuthBindingUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := useroauthbinding.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserOAuthBinding.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderUserID(); ok {
		if err := useroauthbinding.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "UserOAuthBinding.provider_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderEmail(); ok {
		if err := useroauthbinding.ProviderEmailValidator(v); err != nil {
			return &ValidationError{Name: "provider_email", err: fmt.Errorf(`ent: validator failed for field "UserOAuthBinding.provider_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderUsername(); ok {
		if err := useroauthbinding.ProviderUsernameValidator(v); err != nil {
			return &ValidationError{Name: "provider_username", err: fmt.Errorf(`ent: validator failed for field "UserOAuthBinding.provider_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderAvatar(); ok {
		if err := useroauthbinding.ProviderAvatarValidator(v); err != nil {
			return &ValidationError{Name: "provider_avatar", err: fmt.Errorf(`ent: validator failed for field "UserOAuthBinding.provider_avatar": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserOAuthBinding.user"`)
	}
	return nil
}

func (_u *UserOAuthBindingUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useroauthbinding.Table, useroauthbinding.Columns, sqlgraph.NewFieldSpec(useroauthbinding.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(useroauthbinding.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderUserID(); ok {
		_spec.SetField(useroauthbinding.FieldProviderUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderEmail(); ok {
		_spec.SetField(useroauthbinding.FieldProviderEmail, field.TypeString, value)
	}
	if _u.mutation.ProviderEmailCleared() {
		_spec.ClearField(useroauthbinding.FieldProviderEmail, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderUsername(); ok {
		_spec.SetField(useroauthbinding.FieldProviderUsername, field.TypeString, value)
	}
	if _u.mutation.ProviderUsernameCleared() {
		_spec.ClearField(useroauthbinding.FieldProviderUsername, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderAvatar(); ok {
		_spec.SetField(useroauthbinding.FieldProviderAvatar, field.TypeString, value)
	}
	if _u.mutation.ProviderAvatarCleared() {
		_spec.ClearField(useroauthbinding.FieldProviderAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(useroauthbinding.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(useroauthbinding.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(useroauthbinding.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(useroauthbinding.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useroauthbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useroauthbinding.UserTable,
			Columns: []string{useroauthbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useroauthbinding.UserTable,
			Columns: []string{useroauthbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useroauthbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserOAuthBindingUpdateOne is the builder for updating a single UserOAuthBinding entity.
type UserOAuthBindingUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserOAuthBindingMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserOAuthBindingUpdateOne) SetUserID(v int64) *UserOAuthBindingUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserOAuthBindingUpdateOne) SetNillableUserID(v *int64) *UserOAuthBindingUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetProvider sets the "provider" field.
func (_u *UserOAuthBindingUpdateOne) SetProvider(v string) *UserOAuthBindingUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *UserOAuthBindingUpdateOne) SetNillableProvider(v *string) *UserOAuthBindingUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetProviderUserID sets the "provider_user_id" field.
func (_u *UserOAuthBindingUpdateOne) SetProviderUserID(v string) *UserOAuthBindingUpdateOne {
	_u.mutation.SetProviderUserID(v)
	return _u
}

// SetNillableProviderUserID sets the "provider_user_id" field if the given value is not nil.
func (_u *UserOAuthBindingUpdateOne) SetNillableProviderUserID(v *string) *UserOAuthBindingUpdateOne {
	if v != nil {
		_u.SetProviderUserID(*v)
	}
	return _u
}

// SetProviderEmail sets the "provider_email" field.
func (_u *UserOAuthBindingUpdateOne) SetProviderEmail(v string) *UserOAuthBindingUpdateOne {
	_u.mutation.SetProviderEmail(v)
	return _u
}

// SetNillableProviderEmail sets the "provider_email" field if the given value is not nil.
func (_u *UserOAuthBindingUpdateOne) SetNillableProviderEmail(v *string) *UserOAuthBindingUpdateOne {
	if v != nil {
		_u.SetProviderEmail(*v)
	}
	return _u
}

// ClearProviderEmail clears the value of the "provider_email" field.
func (_u *UserOAuthBindingUpdateOne) ClearProviderEmail() *UserOAuthBindingUpdateOne {
	_u.mutation.ClearProviderEmail()
	return _u
}

// SetProviderUsername sets the "provider_username" field.
func (_u *UserOAuthBindingUpdateOne) SetProviderUsername(v string) *UserOAuthBindingUpdateOne {
	_u.mutation.SetProviderUsername(v)
	return _u
}

// SetNillableProviderUsername sets the "provider_username" field if the given value is not nil.
func (_u *UserOAuthBindingUpdateOne) SetNillableProviderUsername(v *string) *UserOAuthBindingUpdateOne {
	if v != nil {
		_u.SetProviderUsername(*v)
	}
	return _u
}

// ClearProviderUsername clears the value of the "provider_username" field.
func (_u *UserOAuthBindingUpdateOne) ClearProviderUsername() *UserOAuthBindingUpdateOne {
	_u.mutation.ClearProviderUsername()
	return _u
}

// SetProviderAvatar sets the "provider_avatar" field.
func (_u *UserOAuthBindingUpdateOne) SetProviderAvatar(v string) *UserOAuthBindingUpdateOne {
	_u.mutation.SetProviderAvatar(v)
	return _u
}

// SetNillableProviderAvatar sets the "provider_avatar" field if the given value is not nil.
func (_u *UserOAuthBindingUpdateOne) SetNillableProviderAvatar(v *string) *UserOAuthBindingUpdateOne {
	if v != nil {
		_u.SetProviderAvatar(*v)
	}
	return _u
}

// ClearProviderAvatar clears the value of the "provider_avatar" field.
func (_u *UserOAuthBindingUpdateOne) ClearProviderAvatar() *UserOAuthBindingUpdateOne {
	_u.mutation.ClearProviderAvatar()
	return _u
}

// SetAccessToken sets the "access_token" field.
func (_u *UserOAuthBindingUpdateOne) SetAccessToken(v string) *UserOAuthBindingUpdateOne {
	_u.mutation.SetAccessToken(v)
	return _u
}

// SetNillableAccessToken sets the "access_token" field if the given value is not nil.
func (_u *UserOAuthBindingUpdateOne) SetNillableAccessToken(v *string) *UserOAuthBindingUpdateOne {
	if v != nil {
		_u.SetAccessToken(*v)
	}
	return _u
}

// ClearAccessToken clears the value of the "access_token" field.
func (_u *UserOAuthBindingUpdateOne) ClearAccessToken() *UserOAuthBindingUpdateOne {
	_u.mutation.ClearAccessToken()
	return _u
}

// SetRefreshToken sets the "refresh_token" field.
func (_u *UserOAuthBindingUpdateOne) SetRefreshToken(v string) *UserOAuthBindingUpdateOne {
	_u.mutation.SetRefreshToken(v)
	return _u
}

// SetNillableRefreshToken sets the "refresh_token" field if the given value is not nil.
func (_u *UserOAuthBindingUpdateOne) SetNillableRefreshToken(v *string) *UserOAuthBindingUpdateOne {
	if v != nil {
		_u.SetRefreshToken(*v)
	}
	return _u
}

// ClearRefreshToken clears the value of the "refresh_token" field.
func (_u *UserOAuthBindingUpdateOne) ClearRefreshToken() *UserOAuthBindingUpdateOne {
	_u.mutation.ClearRefreshToken()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UserOAuthBindingUpdateOne) SetUpdatedAt(v time.Time) *UserOAuthBindingUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserOAuthBindingUpdateOne) SetUser(v *User) *UserOAuthBindingUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the UserOAuthBindingMutation object of the builder.
func (_u *UserOAuthBindingUpdateOne) Mutation() *UserOAuthBindingMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserOAuthBindingUpdateOne) ClearUser() *UserOAuthBindingUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the UserOAuthBindingUpdate builder.
func (_u *UserOAuthBindingUpdateOne) Where(ps ...predicate.UserOAuthBinding) *UserOAuthBindingUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserOAuthBindingUpdateOne) Select(field string, fields ...string) *UserOAuthBindingUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserOAuthBinding entity.
func (_u *UserOAuthBindingUpdateOne) Save(ctx context.Context) (*UserOAuthBinding, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserOAuthBindingUpdateOne) SaveX(ctx context.Context) *UserOAuthBinding {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserOAuthBindingUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserOAuthBindingUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UserOAuthBindingUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := useroauthbinding.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserOAuthBindingUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := useroauthbinding.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserOAuthBinding.provider": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderUserID(); ok {
		if err := useroauthbinding.ProviderUserIDValidator(v); err != nil {
			return &ValidationError{Name: "provider_user_id", err: fmt.Errorf(`ent: validator failed for field "UserOAuthBinding.provider_user_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderEmail(); ok {
		if err := useroauthbinding.ProviderEmailValidator(v); err != nil {
			return &ValidationError{Name: "provider_email", err: fmt.Errorf(`ent: validator failed for field "UserOAuthBinding.provider_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderUsername(); ok {
		if err := useroauthbinding.ProviderUsernameValidator(v); err != nil {
			return &ValidationError{Name: "provider_username", err: fmt.Errorf(`ent: validator failed for field "UserOAuthBinding.provider_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProviderAvatar(); ok {
		if err := useroauthbinding.ProviderAvatarValidator(v); err != nil {
			return &ValidationError{Name: "provider_avatar", err: fmt.Errorf(`ent: validator failed for field "UserOAuthBinding.provider_avatar": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserOAuthBinding.user"`)
	}
	return nil
}

func (_u *UserOAuthBindingUpdateOne) sqlSave(ctx context.Context) (_node *UserOAuthBinding, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(useroauthbinding.Table, useroauthbinding.Columns, sqlgraph.NewFieldSpec(useroauthbinding.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UserOAuthBinding.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, useroauthbinding.FieldID)
		for _, f := range fields {
			if !useroauthbinding.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != useroauthbinding.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(useroauthbinding.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderUserID(); ok {
		_spec.SetField(useroauthbinding.FieldProviderUserID, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProviderEmail(); ok {
		_spec.SetField(useroauthbinding.FieldProviderEmail, field.TypeString, value)
	}
	if _u.mutation.ProviderEmailCleared() {
		_spec.ClearField(useroauthbinding.FieldProviderEmail, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderUsername(); ok {
		_spec.SetField(useroauthbinding.FieldProviderUsername, field.TypeString, value)
	}
	if _u.mutation.ProviderUsernameCleared() {
		_spec.ClearField(useroauthbinding.FieldProviderUsername, field.TypeString)
	}
	if value, ok := _u.mutation.ProviderAvatar(); ok {
		_spec.SetField(useroauthbinding.FieldProviderAvatar, field.TypeString, value)
	}
	if _u.mutation.ProviderAvatarCleared() {
		_spec.ClearField(useroauthbinding.FieldProviderAvatar, field.TypeString)
	}
	if value, ok := _u.mutation.AccessToken(); ok {
		_spec.SetField(useroauthbinding.FieldAccessToken, field.TypeString, value)
	}
	if _u.mutation.AccessTokenCleared() {
		_spec.ClearField(useroauthbinding.FieldAccessToken, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshToken(); ok {
		_spec.SetField(useroauthbinding.FieldRefreshToken, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenCleared() {
		_spec.ClearField(useroauthbinding.FieldRefreshToken, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(useroauthbinding.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useroauthbinding.UserTable,
			Columns: []string{useroauthbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   useroauthbinding.UserTable,
			Columns: []string{useroauthbinding.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserOAuthBinding{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{useroauthbinding.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
