// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/useroauthbinding"
)

// UserOAuthBinding is the model entity for the UserOAuthBinding schema.
type UserOAuthBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// 用户ID
	UserID int64 `json:"user_id,omitempty"`
	// 提供商标识: google, github
	Provider string `json:"provider,omitempty"`
	// 第三方平台用户ID
	ProviderUserID string `json:"provider_user_id,omitempty"`
	// 第三方平台邮箱
	ProviderEmail *string `json:"provider_email,omitempty"`
	// 第三方平台用户名
	ProviderUsername *string `json:"provider_username,omitempty"`
	// 第三方平台头像URL
	ProviderAvatar *string `json:"provider_avatar,omitempty"`
	// 访问令牌（可选存储）
	AccessToken *string `json:"-"`
	// 刷新令牌（可选存储）
	RefreshToken *string `json:"-"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserOAuthBindingQuery when eager-loading is set.
	Edges        UserOAuthBindingEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserOAuthBindingEdges holds the relations/edges for other nodes in the graph.
type UserOAuthBindingEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserOAuthBindingEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UserOAuthBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case useroauthbinding.FieldID, useroauthbinding.FieldUserID:
			values[i] = new(sql.NullInt64)
		case useroauthbinding.FieldProvider, useroauthbinding.FieldProviderUserID, useroauthbinding.FieldProviderEmail, useroauthbinding.FieldProviderUsername, useroauthbinding.FieldProviderAvatar, useroauthbinding.FieldAccessToken, useroauthbinding.FieldRefreshToken:
			values[i] = new(sql.NullString)
		case useroauthbinding.FieldCreatedAt, useroauthbinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UserOAuthBinding fields.
func (_m *UserOAuthBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case useroauthbinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case useroauthbinding.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case useroauthbinding.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case useroauthbinding.FieldProviderUserID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_user_id", values[i])
			} else if value.Valid {
				_m.ProviderUserID = value.String
			}
		case useroauthbinding.FieldProviderEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_email", values[i])
			} else if value.Valid {
				_m.ProviderEmail = new(string)
				*_m.ProviderEmail = value.String
			}
		case useroauthbinding.FieldProviderUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_username", values[i])
			} else if value.Valid {
				_m.ProviderUsername = new(string)
				*_m.ProviderUsername = value.String
			}
		case useroauthbinding.FieldProviderAvatar:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_avatar", values[i])
			} else if value.Valid {
				_m.ProviderAvatar = new(string)
				*_m.ProviderAvatar = value.String
			}
		case useroauthbinding.FieldAccessToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token", values[i])
			} else if value.Valid {
				_m.AccessToken = new(string)
				*_m.AccessToken = value.String
			}
		case useroauthbinding.FieldRefreshToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token", values[i])
			} else if value.Valid {
				_m.RefreshToken = new(string)
				*_m.RefreshToken = value.String
			}
		case useroauthbinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case useroauthbinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UserOAuthBinding.
// This includes values selected through modifiers, order, etc.
func (_m *UserOAuthBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the UserOAuthBinding entity.
func (_m *UserOAuthBinding) QueryUser() *UserQuery {
	return NewUserOAuthBindingClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this UserOAuthBinding.
// Note that you need to call UserOAuthBinding.Unwrap() before calling this method if this UserOAuthBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UserOAuthBinding) Update() *UserOAuthBindingUpdateOne {
	return NewUserOAuthBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UserOAuthBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UserOAuthBinding) Unwrap() *UserOAuthBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UserOAuthBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UserOAuthBinding) String() string {
	var builder strings.Builder
	builder.WriteString("UserOAuthBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("provider_user_id=")
	builder.WriteString(_m.ProviderUserID)
	builder.WriteString(", ")
	if v := _m.ProviderEmail; v != nil {
		builder.WriteString("provider_email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProviderUsername; v != nil {
		builder.WriteString("provider_username=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProviderAvatar; v != nil {
		builder.WriteString("provider_avatar=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("access_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("refresh_token=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// UserOAuthBindings is a parsable slice of UserOAuthBinding.
type UserOAuthBindings []*UserOAuthBinding
