// Code generated by ent, DO NOT EDIT.

package useroauthbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the useroauthbinding type in the database.
	Label = "user_oauth_binding"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldProvider holds the string denoting the provider field in the database.
	FieldProvider = "provider"
	// FieldProviderUserID holds the string denoting the provider_user_id field in the database.
	FieldProviderUserID = "provider_user_id"
	// FieldProviderEmail holds the string denoting the provider_email field in the database.
	FieldProviderEmail = "provider_email"
	// FieldProviderUsername holds the string denoting the provider_username field in the database.
	FieldProviderUsername = "provider_username"
	// FieldProviderAvatar holds the string denoting the provider_avatar field in the database.
	FieldProviderAvatar = "provider_avatar"
	// FieldAccessToken holds the string denoting the access_token field in the database.
	FieldAccessToken = "access_token"
	// FieldRefreshToken holds the string denoting the refresh_token field in the database.
	FieldRefreshToken = "refresh_token"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the useroauthbinding in the database.
	Table = "user_oauth_bindings"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "user_oauth_bindings"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for useroauthbinding fields.
var Columns = []string{
	FieldID,
	FieldUserID,
	FieldProvider,
	FieldProviderUserID,
	FieldProviderEmail,
	FieldProviderUsername,
	FieldProviderAvatar,
	FieldAccessToken,
	FieldRefreshToken,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// ProviderValidator is a validator for the "provider" field. It is called by the builders before save.
	ProviderValidator func(string) error
	// ProviderUserIDValidator is a validator for the "provider_user_id" field. It is called by the builders before save.
	ProviderUserIDValidator func(string) error
	// ProviderEmailValidator is a validator for the "provider_email" field. It is called by the builders before save.
	ProviderEmailValidator func(string) error
	// ProviderUsernameValidator is a validator for the "provider_username" field. It is called by the builders before save.
	ProviderUsernameValidator func(string) error
	// ProviderAvatarValidator is a validator for the "provider_avatar" field. It is called by the builders before save.
	ProviderAvatarValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the UserOAuthBinding queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByProvider orders the results by the provider field.
func ByProvider(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProvider, opts...).ToFunc()
}

// ByProviderUserID orders the results by the provider_user_id field.
func ByProviderUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderUserID, opts...).ToFunc()
}

// ByProviderEmail orders the results by the provider_email field.
func ByProviderEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderEmail, opts...).ToFunc()
}

// ByProviderUsername orders the results by the provider_username field.
func ByProviderUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderUsername, opts...).ToFunc()
}

// ByProviderAvatar orders the results by the provider_avatar field.
func ByProviderAvatar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderAvatar, opts...).ToFunc()
}

// ByAccessToken orders the results by the access_token field.
func ByAccessToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessToken, opts...).ToFunc()
}

// ByRefreshToken orders the results by the refresh_token field.
func ByRefreshToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshToken, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
