// Code generated by ent, DO NOT EDIT.

package useroauthbinding

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldUserID, v))
}

// Provider applies equality check predicate on the "provider" field. It's identical to ProviderEQ.
func Provider(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldProvider, v))
}

// ProviderUserID applies equality check predicate on the "provider_user_id" field. It's identical to ProviderUserIDEQ.
func ProviderUserID(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldProviderUserID, v))
}

// ProviderEmail applies equality check predicate on the "provider_email" field. It's identical to ProviderEmailEQ.
func ProviderEmail(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldProviderEmail, v))
}

// ProviderUsername applies equality check predicate on the "provider_username" field. It's identical to ProviderUsernameEQ.
func ProviderUsername(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldProviderUsername, v))
}

// ProviderAvatar applies equality check predicate on the "provider_avatar" field. It's identical to ProviderAvatarEQ.
func ProviderAvatar(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldProviderAvatar, v))
}

// AccessToken applies equality check predicate on the "access_token" field. It's identical to AccessTokenEQ.
func AccessToken(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldAccessToken, v))
}

// RefreshToken applies equality check predicate on the "refresh_token" field. It's identical to RefreshTokenEQ.
func RefreshToken(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldRefreshToken, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldUserID, vs...))
}

// ProviderEQ applies the EQ predicate on the "provider" field.
func ProviderEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldProvider, v))
}

// ProviderNEQ applies the NEQ predicate on the "provider" field.
func ProviderNEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldProvider, v))
}

// ProviderIn applies the In predicate on the "provider" field.
func ProviderIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldProvider, vs...))
}

// ProviderNotIn applies the NotIn predicate on the "provider" field.
func ProviderNotIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldProvider, vs...))
}

// ProviderGT applies the GT predicate on the "provider" field.
func ProviderGT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGT(FieldProvider, v))
}

// ProviderGTE applies the GTE predicate on the "provider" field.
func ProviderGTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGTE(FieldProvider, v))
}

// ProviderLT applies the LT predicate on the "provider" field.
func ProviderLT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLT(FieldProvider, v))
}

// ProviderLTE applies the LTE predicate on the "provider" field.
func ProviderLTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLTE(FieldProvider, v))
}

// ProviderContains applies the Contains predicate on the "provider" field.
func ProviderContains(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContains(FieldProvider, v))
}

// ProviderHasPrefix applies the HasPrefix predicate on the "provider" field.
func ProviderHasPrefix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasPrefix(FieldProvider, v))
}

// ProviderHasSuffix applies the HasSuffix predicate on the "provider" field.
func ProviderHasSuffix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasSuffix(FieldProvider, v))
}

// ProviderEqualFold applies the EqualFold predicate on the "provider" field.
func ProviderEqualFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEqualFold(FieldProvider, v))
}

// ProviderContainsFold applies the ContainsFold predicate on the "provider" field.
func ProviderContainsFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContainsFold(FieldProvider, v))
}

// ProviderUserIDEQ applies the EQ predicate on the "provider_user_id" field.
func ProviderUserIDEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldProviderUserID, v))
}

// ProviderUserIDNEQ applies the NEQ predicate on the "provider_user_id" field.
func ProviderUserIDNEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldProviderUserID, v))
}

// ProviderUserIDIn applies the In predicate on the "provider_user_id" field.
func ProviderUserIDIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldProviderUserID, vs...))
}

// ProviderUserIDNotIn applies the NotIn predicate on the "provider_user_id" field.
func ProviderUserIDNotIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldProviderUserID, vs...))
}

// ProviderUserIDGT applies the GT predicate on the "provider_user_id" field.
func ProviderUserIDGT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGT(FieldProviderUserID, v))
}

// ProviderUserIDGTE applies the GTE predicate on the "provider_user_id" field.
func ProviderUserIDGTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGTE(FieldProviderUserID, v))
}

// ProviderUserIDLT applies the LT predicate on the "provider_user_id" field.
func ProviderUserIDLT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLT(FieldProviderUserID, v))
}

// ProviderUserIDLTE applies the LTE predicate on the "provider_user_id" field.
func ProviderUserIDLTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLTE(FieldProviderUserID, v))
}

// ProviderUserIDContains applies the Contains predicate on the "provider_user_id" field.
func ProviderUserIDContains(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContains(FieldProviderUserID, v))
}

// ProviderUserIDHasPrefix applies the HasPrefix predicate on the "provider_user_id" field.
func ProviderUserIDHasPrefix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasPrefix(FieldProviderUserID, v))
}

// ProviderUserIDHasSuffix applies the HasSuffix predicate on the "provider_user_id" field.
func ProviderUserIDHasSuffix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasSuffix(FieldProviderUserID, v))
}

// ProviderUserIDEqualFold applies the EqualFold predicate on the "provider_user_id" field.
func ProviderUserIDEqualFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEqualFold(FieldProviderUserID, v))
}

// ProviderUserIDContainsFold applies the ContainsFold predicate on the "provider_user_id" field.
func ProviderUserIDContainsFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContainsFold(FieldProviderUserID, v))
}

// ProviderEmailEQ applies the EQ predicate on the "provider_email" field.
func ProviderEmailEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldProviderEmail, v))
}

// ProviderEmailNEQ applies the NEQ predicate on the "provider_email" field.
func ProviderEmailNEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldProviderEmail, v))
}

// ProviderEmailIn applies the In predicate on the "provider_email" field.
func ProviderEmailIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldProviderEmail, vs...))
}

// ProviderEmailNotIn applies the NotIn predicate on the "provider_email" field.
func ProviderEmailNotIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldProviderEmail, vs...))
}

// ProviderEmailGT applies the GT predicate on the "provider_email" field.
func ProviderEmailGT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGT(FieldProviderEmail, v))
}

// ProviderEmailGTE applies the GTE predicate on the "provider_email" field.
func ProviderEmailGTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGTE(FieldProviderEmail, v))
}

// ProviderEmailLT applies the LT predicate on the "provider_email" field.
func ProviderEmailLT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLT(FieldProviderEmail, v))
}

// ProviderEmailLTE applies the LTE predicate on the "provider_email" field.
func ProviderEmailLTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLTE(FieldProviderEmail, v))
}

// ProviderEmailContains applies the Contains predicate on the "provider_email" field.
func ProviderEmailContains(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContains(FieldProviderEmail, v))
}

// ProviderEmailHasPrefix applies the HasPrefix predicate on the "provider_email" field.
func ProviderEmailHasPrefix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasPrefix(FieldProviderEmail, v))
}

// ProviderEmailHasSuffix applies the HasSuffix predicate on the "provider_email" field.
func ProviderEmailHasSuffix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasSuffix(FieldProviderEmail, v))
}

// ProviderEmailIsNil applies the IsNil predicate on the "provider_email" field.
func ProviderEmailIsNil() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIsNull(FieldProviderEmail))
}

// ProviderEmailNotNil applies the NotNil predicate on the "provider_email" field.
func ProviderEmailNotNil() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotNull(FieldProviderEmail))
}

// ProviderEmailEqualFold applies the EqualFold predicate on the "provider_email" field.
func ProviderEmailEqualFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEqualFold(FieldProviderEmail, v))
}

// ProviderEmailContainsFold applies the ContainsFold predicate on the "provider_email" field.
func ProviderEmailContainsFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContainsFold(FieldProviderEmail, v))
}

// ProviderUsernameEQ applies the EQ predicate on the "provider_username" field.
func ProviderUsernameEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldProviderUsername, v))
}

// ProviderUsernameNEQ applies the NEQ predicate on the "provider_username" field.
func ProviderUsernameNEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldProviderUsername, v))
}

// ProviderUsernameIn applies the In predicate on the "provider_username" field.
func ProviderUsernameIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldProviderUsername, vs...))
}

// ProviderUsernameNotIn applies the NotIn predicate on the "provider_username" field.
func ProviderUsernameNotIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldProviderUsername, vs...))
}

// ProviderUsernameGT applies the GT predicate on the "provider_username" field.
func ProviderUsernameGT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGT(FieldProviderUsername, v))
}

// ProviderUsernameGTE applies the GTE predicate on the "provider_username" field.
func ProviderUsernameGTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGTE(FieldProviderUsername, v))
}

// ProviderUsernameLT applies the LT predicate on the "provider_username" field.
func ProviderUsernameLT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLT(FieldProviderUsername, v))
}

// ProviderUsernameLTE applies the LTE predicate on the "provider_username" field.
func ProviderUsernameLTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLTE(FieldProviderUsername, v))
}

// ProviderUsernameContains applies the Contains predicate on the "provider_username" field.
func ProviderUsernameContains(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContains(FieldProviderUsername, v))
}

// ProviderUsernameHasPrefix applies the HasPrefix predicate on the "provider_username" field.
func ProviderUsernameHasPrefix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasPrefix(FieldProviderUsername, v))
}

// ProviderUsernameHasSuffix applies the HasSuffix predicate on the "provider_username" field.
func ProviderUsernameHasSuffix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasSuffix(FieldProviderUsername, v))
}

// ProviderUsernameIsNil applies the IsNil predicate on the "provider_username" field.
func ProviderUsernameIsNil() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIsNull(FieldProviderUsername))
}

// ProviderUsernameNotNil applies the NotNil predicate on the "provider_username" field.
func ProviderUsernameNotNil() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotNull(FieldProviderUsername))
}

// ProviderUsernameEqualFold applies the EqualFold predicate on the "provider_username" field.
func ProviderUsernameEqualFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEqualFold(FieldProviderUsername, v))
}

// ProviderUsernameContainsFold applies the ContainsFold predicate on the "provider_username" field.
func ProviderUsernameContainsFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContainsFold(FieldProviderUsername, v))
}

// ProviderAvatarEQ applies the EQ predicate on the "provider_avatar" field.
func ProviderAvatarEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldProviderAvatar, v))
}

// ProviderAvatarNEQ applies the NEQ predicate on the "provider_avatar" field.
func ProviderAvatarNEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldProviderAvatar, v))
}

// ProviderAvatarIn applies the In predicate on the "provider_avatar" field.
func ProviderAvatarIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldProviderAvatar, vs...))
}

// ProviderAvatarNotIn applies the NotIn predicate on the "provider_avatar" field.
func ProviderAvatarNotIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldProviderAvatar, vs...))
}

// ProviderAvatarGT applies the GT predicate on the "provider_avatar" field.
func ProviderAvatarGT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGT(FieldProviderAvatar, v))
}

// ProviderAvatarGTE applies the GTE predicate on the "provider_avatar" field.
func ProviderAvatarGTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGTE(FieldProviderAvatar, v))
}

// ProviderAvatarLT applies the LT predicate on the "provider_avatar" field.
func ProviderAvatarLT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLT(FieldProviderAvatar, v))
}

// ProviderAvatarLTE applies the LTE predicate on the "provider_avatar" field.
func ProviderAvatarLTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLTE(FieldProviderAvatar, v))
}

// ProviderAvatarContains applies the Contains predicate on the "provider_avatar" field.
func ProviderAvatarContains(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContains(FieldProviderAvatar, v))
}

// ProviderAvatarHasPrefix applies the HasPrefix predicate on the "provider_avatar" field.
func ProviderAvatarHasPrefix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasPrefix(FieldProviderAvatar, v))
}

// ProviderAvatarHasSuffix applies the HasSuffix predicate on the "provider_avatar" field.
func ProviderAvatarHasSuffix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasSuffix(FieldProviderAvatar, v))
}

// ProviderAvatarIsNil applies the IsNil predicate on the "provider_avatar" field.
func ProviderAvatarIsNil() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIsNull(FieldProviderAvatar))
}

// ProviderAvatarNotNil applies the NotNil predicate on the "provider_avatar" field.
func ProviderAvatarNotNil() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotNull(FieldProviderAvatar))
}

// ProviderAvatarEqualFold applies the EqualFold predicate on the "provider_avatar" field.
func ProviderAvatarEqualFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEqualFold(FieldProviderAvatar, v))
}

// ProviderAvatarContainsFold applies the ContainsFold predicate on the "provider_avatar" field.
func ProviderAvatarContainsFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContainsFold(FieldProviderAvatar, v))
}

// AccessTokenEQ applies the EQ predicate on the "access_token" field.
func AccessTokenEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldAccessToken, v))
}

// AccessTokenNEQ applies the NEQ predicate on the "access_token" field.
func AccessTokenNEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldAccessToken, v))
}

// AccessTokenIn applies the In predicate on the "access_token" field.
func AccessTokenIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldAccessToken, vs...))
}

// AccessTokenNotIn applies the NotIn predicate on the "access_token" field.
func AccessTokenNotIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldAccessToken, vs...))
}

// AccessTokenGT applies the GT predicate on the "access_token" field.
func AccessTokenGT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGT(FieldAccessToken, v))
}

// AccessTokenGTE applies the GTE predicate on the "access_token" field.
func AccessTokenGTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGTE(FieldAccessToken, v))
}

// AccessTokenLT applies the LT predicate on the "access_token" field.
func AccessTokenLT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLT(FieldAccessToken, v))
}

// AccessTokenLTE applies the LTE predicate on the "access_token" field.
func AccessTokenLTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLTE(FieldAccessToken, v))
}

// AccessTokenContains applies the Contains predicate on the "access_token" field.
func AccessTokenContains(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContains(FieldAccessToken, v))
}

// AccessTokenHasPrefix applies the HasPrefix predicate on the "access_token" field.
func AccessTokenHasPrefix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasPrefix(FieldAccessToken, v))
}

// AccessTokenHasSuffix applies the HasSuffix predicate on the "access_token" field.
func AccessTokenHasSuffix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasSuffix(FieldAccessToken, v))
}

// AccessTokenIsNil applies the IsNil predicate on the "access_token" field.
func AccessTokenIsNil() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIsNull(FieldAccessToken))
}

// AccessTokenNotNil applies the NotNil predicate on the "access_token" field.
func AccessTokenNotNil() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotNull(FieldAccessToken))
}

// AccessTokenEqualFold applies the EqualFold predicate on the "access_token" field.
func AccessTokenEqualFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEqualFold(FieldAccessToken, v))
}

// AccessTokenContainsFold applies the ContainsFold predicate on the "access_token" field.
func AccessTokenContainsFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContainsFold(FieldAccessToken, v))
}

// RefreshTokenEQ applies the EQ predicate on the "refresh_token" field.
func RefreshTokenEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldRefreshToken, v))
}

// RefreshTokenNEQ applies the NEQ predicate on the "refresh_token" field.
func RefreshTokenNEQ(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldRefreshToken, v))
}

// RefreshTokenIn applies the In predicate on the "refresh_token" field.
func RefreshTokenIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldRefreshToken, vs...))
}

// RefreshTokenNotIn applies the NotIn predicate on the "refresh_token" field.
func RefreshTokenNotIn(vs ...string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldRefreshToken, vs...))
}

// RefreshTokenGT applies the GT predicate on the "refresh_token" field.
func RefreshTokenGT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGT(FieldRefreshToken, v))
}

// RefreshTokenGTE applies the GTE predicate on the "refresh_token" field.
func RefreshTokenGTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGTE(FieldRefreshToken, v))
}

// RefreshTokenLT applies the LT predicate on the "refresh_token" field.
func RefreshTokenLT(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLT(FieldRefreshToken, v))
}

// RefreshTokenLTE applies the LTE predicate on the "refresh_token" field.
func RefreshTokenLTE(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLTE(FieldRefreshToken, v))
}

// RefreshTokenContains applies the Contains predicate on the "refresh_token" field.
func RefreshTokenContains(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContains(FieldRefreshToken, v))
}

// RefreshTokenHasPrefix applies the HasPrefix predicate on the "refresh_token" field.
func RefreshTokenHasPrefix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasPrefix(FieldRefreshToken, v))
}

// RefreshTokenHasSuffix applies the HasSuffix predicate on the "refresh_token" field.
func RefreshTokenHasSuffix(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldHasSuffix(FieldRefreshToken, v))
}

// RefreshTokenIsNil applies the IsNil predicate on the "refresh_token" field.
func RefreshTokenIsNil() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIsNull(FieldRefreshToken))
}

// RefreshTokenNotNil applies the NotNil predicate on the "refresh_token" field.
func RefreshTokenNotNil() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotNull(FieldRefreshToken))
}

// RefreshTokenEqualFold applies the EqualFold predicate on the "refresh_token" field.
func RefreshTokenEqualFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEqualFold(FieldRefreshToken, v))
}

// RefreshTokenContainsFold applies the ContainsFold predicate on the "refresh_token" field.
func RefreshTokenContainsFold(v string) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldContainsFold(FieldRefreshToken, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserOAuthBinding) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserOAuthBinding) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserOAuthBinding) predicate.UserOAuthBinding {
	return predicate.UserOAuthBinding(sql.NotPredicates(p))
}
